version: '3'
services:

  tunitronc-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - './npm_logs:/root/.npm/_logs'
    networks:
      - docker_TuniTroncNetwork

networks:
  docker_TuniTroncNetwork:
     external: true